### ISSUE TITLE
Ordenar en funciones el llamado a la funcion de llamado a la DBAPI para su mejor uso.

### ISSUE THREAD

**Issue by FrankTII** [BeduTeam8/Recepini-V1#11]
Hasta ahora se han empleado dos formas de llamar a la API.

function (con todos los params) callDBAPI(params)
function (que obtiene los params del DOM) Esta esta en desarrollo en indexSearchBox.html 
Falta desarrollarle para que se emplee en otras busquedas y llame a la funcion desarrollada inicialmente.
Asi se encapsulan datos, se mejora la programación y el código es mas legible.
Esto porque existen llamadas como random.php, random de 10 y latest.php que no requieren parametros. 
Por lo tanto no se requieren llamadas al DOM

Trabajo.
Separa en dos formas el llamado a las funciones

**Comment by FrankTII** [comment]
Se sigue haciendo el trabajo. Su refactoriación o reescritura tumba el sistema por la paralelización de llamadas al API porque Js no es multithread...Mutlihilos es UniThread....así que si paralelizan pensando que hace como en JAVa o C va a fallar.

Al estar reescribiendo las funciones con Async/Await aproveche por ir metiendo manejo del DOM mezclando con InnertHTML. Dejo un newindex.html como prueba de que estan operando sin fallar y con captura de errores

**Comment by rmn-isb** [comment]
Búsqueda por letra del alfabeto y despliegue en result section completado.
