### ISSUE TITLE
Revisar el uso de Promises y llamadas paralelas al inicio de la carga de la app

### ISSUE THREAD

**Issue by FrankTII** [BeduTeam8/Recepini-V1#14]
Investigar el uso de promises y async para cargar los datos del JSON.
Esto implica quizá separar las llamadas al JSON por variable_por_tipo_de_llamada.
Las llamadas hasta este punto del desarrollo lo hacia la misma variable. 
El fetch carga el mismo objeto variable y sobre ese se ha estado trabajando.
Seria ver que variables se cargan una vez y cuales se recargan en cada interacción del usuario con nuestra app.

Esto esta conectado con el issue #11

**Comment by FrankTII** [comment]
Promises es solo el concepto de lo que Fetch regresa.
Fetch siempre regresa responses que son promesas. Puede que se cumplan. puede que no.
Async, obliga a reescribir las funciones porque todo lo que tenga que espera un evento asyncrono (revisar que es event loop) se debe esperar a que lo asyncrono termine. De lo contrario las cosas son indefinidas. 

El problema de promises all es que si una falla el promises.all hace un reject es decir todo falla. (resolve y reject) de los promises.

**Comment by FrankTII** [comment]
Se han incorporado promises.all para el manejo de las llamadas en onload del window, va de la mano con #13 y #11

**Comment by FrankTII** [comment]
Se reescribio el codigo con async/await y promises.all. Hasta esta semana el sistema a estado operando bien. Incluso con las llamadas automaticas ya instaladas.

**Comment by rmn-isb** [comment]
El sistema opera bien con el manejo de llamadas.
