### ISSUE TITLE
Trabajar en el readme.md

### ISSUE THREAD

**Issue by toonchavez8** [BeduTeam8/Recepini-V1#21]
@toonchavez8 y @karlarochae 

El readme ya lo lleva el branch de design system

**Comment by toonchavez8** [comment]
Perfecto muchas gracias dentro de el readme que ya llevó iniciado sería bueno ver unos que te voy a pasar por aquí y ver qué información práctica podemos poner. Igual agrega a los demás porfa a la tarea para que colaboren @karlarochae

**Comment by FrankTII** [comment]
Estoy viendo el READMe.md. 
Muy buena idea la del template.
Pero JQuery? supongo iba con el templete no se lo estamos empleando por el momento solo lleva Vanilla JS
