### ISSUE TITLE
Design the happy path - site map

### ISSUE THREAD

**Issue by toonchavez8** [BeduTeam8/Recepini-V1#23]
Responder las siguentes preguntas flow 
- [x] como seria el flujo del usario dentro de la pagina
- [x] acciones de inicio de como se realiza la busqueda
- [x] como se muestra el resultado
- [x] propuesta de modal

**Comment by toonchavez8** [comment]
@FrankTII agregue el sito de mapa a esta tarea en la tarde inteno tener las paginas listas visualmente y si quieres que lo revisemos en la noche contodo gusto 
 y dependiendo de esa llamada podemos cerrar esta tarea y integrar a main el diseño o si tienes alguna sugerencia mejor con todo gusto. 


![Recepini_Site_Map](https://user-images.githubusercontent.com/104461542/185801730-684aeade-4bfa-4f7c-ab26-3bb5d173d170.png)

**Comment by FrankTII** [comment]
Landing PAGE:

Lo estoy revisando. Es justo lo que necesitamos para darnos una idea. de donde va y adonde podemos llegar. 
Si quieres te adelanto las dudas que tengo y posiblemente Jesus también tendrá.
inicio pagina central superior y bajo. 
Inicio:
__________________________________________________________________________________________________
Random Recipe o Receta Sorpresa.
Se activa con evento de boton y llama a función randomButton o GetRecipe(0). Devuelve un objeto con arreglo de  53 campos. para desplegar una receta a un DIV específico:_____________________.
__________________________________________________________________________________________________
Carrusel de imágenes aleatorias se repite la función si ya tenemos un API con 10 recetas aleatorias.
Si adamas quieren fotos seria llamar al random10 una segunda vez para obtener 10 foto que metemos a un carrusel. Es la forma mas simple de cubrir ese requerimiento. Siento que es una función repetida. 
__________________________________________________________________________________________________
Top 10 recomenciones /10 Recetas aleatorias: llama a la funcion r10recipes() o getRecipes(1) y devuelve el resultado en el DIV 10Aleatorias elegido:____________________________.
__________________________________________________________________________________________________
Looking for Some type of food?/Categorias por paises o ingredientes mas buscados.
Categorias de paises : devuelve un objeto con 27 respuestas, 26 de ellas en su <gentilicio> que deberemos ligar a la bandera. 
El nombre del archivo en assets/ deberá ser el mismo del gentilicio. (usemos el dashboard de Jesus en la búsqueda sugerida)
Desplegamos en el l DIV asigando el resultado de la APi-1 registro(unknown) DIV x Areas/Paises_______________
__________
Los ingredientes más buscados eso los deberemos codificar manualmente una lista de N ingredientes elegidos por nosotros. La foto iria ligada a la busqueda por ingrediente de ese nombre. El resultado de esas busquedas se van al DIV de resultados asignado:________________________
FOOTER
==============================================================

Pagina Receta
Todo el despliegue de la receta aparece por la Busqueda x Id. 
Codigo HTML devuelto al DIV asignado___________________________

Recetas similares: Por le momento desconozco de donde sacar la lista a asignar en está sección.
=================================================================

Pag de busqueda y resultados:
Podemos platicarlo mañana lo de los filtros, Creo que tenemos todo. Es un manejo de mucho eventos para  limitar campos y selecionar busquedas. Las funciones se separaron para este escenario.(Aqui estoy)
Estos resultados deberán desplegarse en los DIV de esta sección.
===============================================================
Si tienes razon que pasa si la busqueda regresa null (no tenemos recetas con esa letras)

Recomiendo: 
a)Opción A es hacer un splice del string con menos letras en el nombre hasta que solo quede un caracter. La busqueda se detiene cuando el JSOn por nombre no se aNULL.
B)opcion B es  disparar la funcion de 10 aleatorias por si le gustaría probar algo diferente. 

En recetas con esos ingredientes, de esos paises, solo se despliegan ingredientes que tenemos en lista.
Hago un branch para SearchBox SearchEngine y les dejo un archivo que use para reeescribir las llamadas al API según patrones que vi. Esta en mi analisis, asi que si no entienden les pido me pregunten.

================================================================
Las famosas Coockies ... quien sabe hacerlas/ usarlas. Serian geniales para las variables de control que tenemos. Algunas con scope global. Y como las lee JS?

**Comment by jesuszdp** [comment]
@toonchavez8 gracias nos sirve mucho.
Colocaste un buen resumen  @FrankTII, solo tengo estos comentarios adicionales.

En caso de que sea null, se podría mostrar la receta del día o como se menciona, el mismo listado que aparece en 10 recetas aleatorias, así nos ahorramos una llamada al API.

Para recetas similares se podría ocupar la consulta de searchxMultiIngredient (consulta 12 de la API). Seleccionar el ingrediente principal y uno extra.

**Comment by toonchavez8** [comment]
![Landing Page Mobile](https://user-images.githubusercontent.com/104461542/186583723-db1ece21-03b9-4478-a7b6-66d68cb9720f.png)
![Receta Page Desktop](https://user-images.githubusercontent.com/104461542/186583730-df5c5cc6-3285-4c42-8b4e-bd8d50cf5034.png)
![Receta Page Mobile](https://user-images.githubusercontent.com/104461542/186583742-1e05945b-7301-4ee8-9882-3a5a7c3f2005.png)
![Receta Page Mobile-1](https://user-images.githubusercontent.com/104461542/186583744-b616278a-538b-4255-a358-183406d61d11.png)
![Search Results Page Desktop](https://user-images.githubusercontent.com/104461542/186583748-07c2864d-d643-4188-8334-25fea7631d12.png)
![Search Results Page Mobile](https://user-images.githubusercontent.com/104461542/186583751-0c0f7d83-4026-440c-8f37-693867edf9eb.png)
![Ingredient Page Desktop](https://user-images.githubusercontent.com/104461542/186583753-0fddbecf-c79b-46b4-87d1-fd847f0b2096.png)
![Ingredient Page Desktop-2](https://user-images.githubusercontent.com/104461542/186583756-5897677c-c903-4c32-9a90-e9de32c458ee.png)
![Landing Page Desktop](https://user-images.githubusercontent.com/104461542/186583758-51987e1a-24be-4f9f-9904-5ca9ce8ee189.png)
